### ISSUE TITLE
Удаление маски

### ISSUE THREAD

**Issue by alekseykurylev** [MaratIldarovich/nice_phone#1]
Добрый день. Подскажите как удалить маску. Например, после того, как убирается фокус с поля маска удаляется и остается placeholder.

**Comment by MaratIldarovich** [comment]
@alekseykurylev Здравствуйте. Можно вызвать метод destroyMask() у экземпляра класса. Включить маску можно будет через new NicePhone(element)

**Comment by Archakov06** [comment]
Спасибо, чувак, за эту либу
